'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages

    Partial Public Class AccountEntry

        '''<summary>
        '''LoginWrapper_PNL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LoginWrapper_PNL As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UserNameLogin_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserNameLogin_View As Global.TmpBank.Controls.LabeledInput

        '''<summary>
        '''PasswordLogin_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PasswordLogin_View As Global.TmpBank.Controls.LabeledInput

        '''<summary>
        '''DigSig_UC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DigSig_UC As Global.TmpBank.Controls.DigitalSigControl

        '''<summary>
        '''LoginBtn_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LoginBtn_View As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''LoginValidationResult_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LoginValidationResult_View As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UsernameSignup_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UsernameSignup_View As Global.TmpBank.Controls.LabeledInput

        '''<summary>
        '''PasswordSignup_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PasswordSignup_View As Global.TmpBank.Controls.LabeledInput

        '''<summary>
        '''EmailSignup_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EmailSignup_View As Global.TmpBank.Controls.LabeledInput

        '''<summary>
        '''SignUpBtn_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SignUpBtn_View As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''SignupValidationResult_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SignupValidationResult_View As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
