'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages

    Partial Public Class Base

        '''<summary>
        '''HeadContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''UserControlScrips control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserControlScrips As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''Login_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Login_View As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Transactions_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Transactions_View As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''SignOut_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SignOut_View As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''MainContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    End Class
End Namespace
