'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages

    Partial Public Class GeneralError

        '''<summary>
        '''ErrorCode_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorCode_View As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ErrorDescription_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorDescription_View As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
