'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Pages

    Partial Public Class FindUser

        '''<summary>
        '''UserFinderPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserFinderPanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''Username_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Username_View As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Submit_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Submit_View As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Result_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Result_View As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''HistoryList_View control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HistoryList_View As Global.System.Web.UI.WebControls.ListView
    End Class
End Namespace
