'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls

    Partial Public Class DigitalSig

        '''<summary>
        '''DigSigWrapper_DIV control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DigSigWrapper_DIV As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''DefaultMarkup_DIV control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DefaultMarkup_DIV As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''NationalCode_UC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NationalCode_UC As Global.TmpBank.Controls.LabeldInput

        '''<summary>
        '''DigitalSignature_RB control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DigitalSignature_RB As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''UsernamePassword_RB control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UsernamePassword_RB As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''Submit_BTN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Submit_BTN As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CustomTemplate_PH control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CustomTemplate_PH As Global.System.Web.UI.WebControls.PlaceHolder
    End Class
End Namespace
